language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
env:
  - SYMFONY_VERSION="2.3.*" FRAMEWORK_EXTRA_BUNDLE_VERSION="*"
  - SYMFONY_VERSION="2.7.*" FRAMEWORK_EXTRA_BUNDLE_VERSION="*"
  - SYMFONY_VERSION="2.8.*" FRAMEWORK_EXTRA_BUNDLE_VERSION="*"
  - SYMFONY_VERSION="3.0.*" FRAMEWORK_EXTRA_BUNDLE_VERSION="*"
matrix:
  exclude:
    - php: 5.3
      env: SYMFONY_VERSION="3.0.*" FRAMEWORK_EXTRA_BUNDLE_VERSION="*"
    - php: 5.4
      env: SYMFONY_VERSION="3.0.*" FRAMEWORK_EXTRA_BUNDLE_VERSION="*"

before_script:
  - composer require --dev --no-interaction symfony/symfony:${SYMFONY_VERSION} sensio/framework-extra-bundle:${FRAMEWORK_EXTRA_BUNDLE_VERSION}
